export interface CustomerDetailsMaster {
    customerId:number;
    firstName:string;
	lastName:string;
	dateOfBirth:string;
	height:string;
	breakFastTime:string;
	lunchFastTime:string;
	eveningSnacksTime:string;
	dinnerTime:string;
	craving:string;
	foodAllergies:string;
	foodPreference:string;
	cookPreference:string;
	typeOfExercise:string;
	injuries:string;
	existingExerciseUser:string;
	exercisePreference:string;
	existingAlcoholUser:string;
	energyLevel:string;
	exercisePreferenceTime:string;
	foodAndExercise:string;
	postalAddress:string;
	callDateAndTime:string;
	extraInfo:string;
	foodExclusive:string;
	gymAccess:string;
	snackingTime:string;
}
